import Head from 'next/head'
import Auctions from '../components/Auctions'
import CricketNft from '../components/CricketNft'
import FootballNft from '../components/FootballNft'
import Header from '../components/Header'
import HockeyNft from '../components/HockeyNft'
import NftCollection from '../components/NftCollection'
import TrandingNft from '../components/TrandingNft'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Player NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Auctions/>
      <TrandingNft/>
      <CricketNft/>
      <FootballNft/>
      <HockeyNft/>
      <NftCollection/>
    </div>
  )
}
