import Head from "next/head";
import Details from "../components/details";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cross chain Wallet Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Details />
    </div>
  );
}
